IDs,Labels,Attribute,Mandatory
ID1,## README,helpText,N
ID2,Data code:,textInput,Y
ID3,Data origin [published or generated]:,textInput,N
ID4,This readme file was generated by [NAME]:,textInput,N
ID5,This readme file was generated on [YYYY-MM-DD]:,textInput,N
ID6,The data is in its original form and has not been processed or cleaned:,checkboxInput,N
ID7,## GENERAL INFORMATION,helpText,N
ID8,Dataset title:,textInput,N
ID9,Description & Purpose:,textAreaInput,N
ID10,Used in projects:,textInput,N
ID11,Who created or downloaded it:,textInput,N
ID12,References publication URL:,textInput,N
ID13,Citation information:,textInput,N
ID14,## SOURCE,helpText,N
ID15,Data source by: <e.g. person/lab generating the data>,textInput,N
ID16,Data source on: <e.g. the data is generated on [YYYY-MM-DD]>,textInput,N
ID17,## DATA FORMAT,helpText,N
ID18,Raw data is available in [data format] named after the convention below and includes the files listed below:,textInput,N
ID19,# Naming convention:,helpText,N
ID20,"	-Structure: <the templet used to name the files (e.g. SXX_Species_Sex_Age.fastq)>",textInput,N
ID21,"	-Codes: <codes/abbreviations used in the name (e.g. XX: unique number per sample, Species: Hs/Mmu/Nfu corresponding to Homo sapiens, Mud muscles, Nothobranchius furze, Sex: M/F corresponding to male/female, Age: [0-29000]>",textAreaInput,N
ID22,"	-Example: <S01_Nfu_M_28.fastq>",textInput,N
ID23,   -List of files: <all files or folders contained in the dataset using regex/folders to prevent overcrowding here> ,textAreaInput,N
ID24,"	-Raw data path in the server:",textInput,N
ID25,"  -Processed data path in the server:",textInput,N
ID26,## DATA GENERATION & METHODOLOGY,helpText,N
ID27,# Description of methods used for collection/generation of data: ,helpText,N
ID28,"	-Method name <DNAseq/RNAseq/scRNAseq/Protein/16S/Meta/others>:",textInput,N
ID29,             -Brief description: <sequencing platform/length etc>,textInput,N
ID30,   -Metainfo Organism <human/mouse/fish/others>,textInput,N
ID31,   -Metainfo Age <range and unit(years, months, days), e.g.,5-9 years>
ID32,   -Metainfo Tissue,textInput,N
ID33,   -Metainfo Model <vivo/vitro/others>,textInput,N
ID34,   -Metainfo Treatment,textInput,N
ID35,   -Metainfo Field <aging/mirobiome/others>,textInput,N
ID36,"	-Method section of the paper:",textAreaInput,N
ID37,             - Prior processing steps if applicable: <e.g. trimming/merging reads etc>,textAreaInput,N
ID38,## DATA DICTIONARY,helpText,N
ID39,Data URL:,textInput,N
ID40,## DATA QUALITY IF APPLICABLE,checkboxInput,N
ID41,Information on data quality including any known issues or errors,textAreaInput,N
ID42,## CONTACT IF APPLICABLE,checkboxInput,N
ID43,"# <If publicly available data, list the corresponding author, If we generated the data, list everyone involved in generation, If a collaborator generated the data, list at least the PI & lead person who generated the data and our lab’s contact person>",helpText,N
ID44,             -Name:,textInput,N
ID45,             -Contribution:,textAreaInput,N
ID46,"	-Institution: <as should be listed in a publication>",textInput,N
ID47,"	-Email:",textInput,N
ID48,## FUNDING IF APPLICABLE,checkboxInput,N
ID49,"	-Grant Number:",textInput,N
ID50,             -Grant Awarded to:,textInput,N
ID51,## LICENCE IF APPLICABLE,checkboxInput,N
ID52,[Licence type] in more details in [licence file name or URL]: <Mention any restrictions on sharing etc>,textAreaInput,N
ID53,## OTHER CONTRIBUTIONS & ACKNOWLEDGEMENT IF APPLICABLE,checkboxInput,N
ID54,Any individuals or organisations who support or contributed to the project in some way,textAreaInput,N
ID55,## ADDITIONAL NOTES IF APPLICABLE,checkboxInput,N
ID56,Additional notes,textAreaInput,N
